### ISSUE TITLE
Item Conversion Error

### ISSUE THREAD

**Issue by BitterBatty** [TexTools/FFXIV_TexTools_UI#115] opened 2021-12-06 16:40 UTC
Also happened when I simply tried to delete and start with a clean install- wouldn't let me delete anything and gave the same error. 

---------------------------
Item Conversion Error
---------------------------
Unable to convert items:

Error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
---------------------------
OK   
---------------------------

What I was doing: Trying to transfer 1 hair to another hair. Specifically a style on hair Aura 103 to Hair Aura 002. 
Received this error. 
Again; thought I messed up something so I tried to "Start Over" through the application. 
Application gave the exact same error. 
Uninstalled program and did clean reinstall. 
Problem persisted.

**Comment by KoraLyn** [comment] 2022-02-07 23:47
Unable to reproduce on my end. This issue would likely be resolved by getting clean index files and starting over.

**Closed as completed by KoraLyn** 2022-02-07 23:47 UTC
