### ISSUE TITLE
[Bug]: Cannot add multiple models from same source to FMV

### ISSUE THREAD

**Issue by Hayden-Fluff** [TexTools/FFXIV_TexTools_UI#275] opened 2023-11-20 12:27 UTC
### Expected behavior?

Whenever I add models to FMV, I'd expect that it would add whatever I have selected, but it seems to replace ones that come from the same source.

### Actual behavior?

Whenever I add a mesh to FMV, it does get added as seen here
![image](https://github.com/TexTools/FFXIV_TexTools_UI/assets/25524760/996870ce-fe7b-4490-8bd5-6ffd3eeacc1d)

However, whenever I change the part and add that, it instead replaces the first part with the new one in FMV
![image](https://github.com/TexTools/FFXIV_TexTools_UI/assets/25524760/967691bc-00ae-47b0-abec-507c03a0b2b0)
Here I attempted to add the hands, but it instead replaced the body with the hands

If there's some configuration to change this behavior, I could not find it after a few minutes of digging around the UI.
This may not be a bug, but in my current case, isn't exactly desirable behavior, I'd prefer to have to remove duplicates in the list myself than have it managed for me.

### Steps to reproduce the problem

1. Go to a model where you can change the part (In this case, Hyur Midlander Male 1)
2. Add the current part to FMV
3. Change the part to something else (in this case changing from the Body to Hands
4. Add this part to FMV
5. The previous part added is instead replaced with the current part.

### Error messages?

No error messages are displayed right away.

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model viewer)
Item: (Hyur Midlander Male)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment] 2023-11-20 21:29
Reproduction steps do not replicate the issue you a re describing.

**Comment by Squall-Leonhart** [comment] 2023-11-20 21:34
The FMV is pretty basic and is intended to demonstrate "Gear", the only Character pieces that should get loaded under "Character" would be the hair, head or tail, the rest you get from the Gear list,

For instance, Character "Head", Character "Tail" + Small clothes Chest, Legs, Hands will get you what you want.

The models under Character Body are low res, low detail stand ins and not really used anywhere in the game.

**Comment by Lunaretic** [comment] 2024-06-05 05:37
This issue seems to be a combination of user error and minor bugs that have been fixed since from refactoring.  Closing issue.

**Closed as completed by Lunaretic** 2024-06-05 05:37 UTC
Labels: bug
