### ISSUE TITLE
[Bug]: color of hair doesn't show

### ISSUE THREAD

**Issue by Dragonia0firiva** [TexTools/FFXIV_TexTools_UI#301] opened 2024-07-10 10:53 UTC
### Expected behavior?

 the colors to blonde and red wich i need for the hair

### Actual behavior?

black and red hair even by changing colours

### Steps to reproduce the problem

1. opened textools
2. made my character until i had the hair section
3. tried to change color
4. no avail

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)

### Has this has been confirmed as an actual bug?

- [ ] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment] 2024-07-10 12:13
pop into the discord, this sounds like an issue with the way you're modding the hair.

**Comment by Lunaretic** [comment] 2024-07-12 18:50
If you added the hair to the FMV first, then changed the hair color, this is because the FMV does not update in real time for those changes, you'd need to re-add the hair item to the FMV after.  (Unsure what you mean by 'Made my character ...' part)

**Comment by Dragonia0firiva** [comment] 2024-07-16 15:53
> If you added the hair to the FMV first, then changed the hair color, this is because the FMV does not update in real time for those changes, you'd need to re-add the hair item to the FMV after. (Unsure what you mean by 'Made my character ...' part)

no i haven't added it first to the fmv i tried to change the color multiple times but nothing

**Comment by Lunaretic** [comment] 2024-07-21 23:59
This does not seem to be reproduceable, and no one else has encountered or reported this issue that I can discover.  Closing this as not-a-bug.  You are most likely either still on EW 2.3.x TexTools or using the application incorrectly.  See discord if you want further support.

**Closed as not planned by Lunaretic** 2024-07-21 23:59 UTC
Labels: bug
