### ISSUE TITLE
[Bug]: Version of FFXIV not supported

### ISSUE THREAD

**Issue by microdd** [TexTools/FFXIV_TexTools_UI#323] opened 2024-11-16 09:39 UTC
### Expected behavior?

Work as supposed

### Actual behavior?

I have the latest version of TT updated and while starting to use it the message below came up

"An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

The given key was not present in the dictionary."

I've tried some earlier versions of TT and got the same results

### Steps to reproduce the problem

1.TT updated after DT update
2.error message came up
3.reinstalled TT, reinstalled FF XIV, still same results
4.tried different earlier versions of TT, same results
5.
...

### Error messages?

"An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

The given key was not present in the dictionary."

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment] 2024-11-16 17:23
dawntrail required starting over prior to patching so that the new  version of TT would start over the modlist from a clean state, if you didn't do that you'll have to delete the modlist json and xiv modcache files from the game folder, closing this as its not a bug.

**Closed as completed by Squall-Leonhart** 2024-11-16 17:23 UTC
Labels: bug

**Comment by microdd** [comment] 2024-11-17 07:48
> dawntrail required starting over prior to patching so that the new version of TT would start over the modlist from a clean state, if you didn't do that you'll have to delete the modlist json and xiv modcache files from the game folder, closing this as its not a bug.

Thanks for the reply, I did the fix but still the same error came up, also while trying to load a body model from Character it says could not find 040000.win32.dat7

**Comment by Squall-Leonhart** [comment] 2024-11-17 16:29
download indexes from the help menu and start over, there is no dat7.

**Comment by microdd** [comment] 2024-11-18 12:08
It says unable to download indexes
