### ISSUE TITLE
Textools Hud acting weird 

### ISSUE THREAD

**Issue by XarXarMinx** [TexTools/FFXIV_TexTools_UI#106] opened 2021-11-15 05:21 UTC
So i completely uninstalled and reinstalled textools because of this and its still doing this

https://user-images.githubusercontent.com/94342498/141726634-e9225740-55bd-4acc-80c1-1389c16eb618.mp4

**Comment by ErisHaumea** [comment] 2021-11-24 16:35
I've had the same issue as shown in this video.  Starting over and uninstalling/reinstalling fresh have not corrected the issue.

**Comment by XarXarMinx** [comment] 2021-11-24 16:51
> I've had the same issue as shown in this video. Starting over and uninstalling/reinstalling fresh have not corrected the issue.

I tried a few things, the only thing that has worked thus far is updating and resetting my computer. fixed a lot of the issues i was having were mods would randomly break or the audio not working in game. Also fixed textools hud

**Comment by Squall-Leonhart** [comment] 2021-12-03 14:29
this is caused by a-volute's nahimic osd injector, not a bug in textools.

**Comment by KoraLyn** [comment] 2022-02-07 23:37
As explained this isn't an issue with TexTools itself so cannot be fixed on our side. I'll leave the issue open for those experiencing similar problems and looking for an explanation.

**Closed as completed** 2022-09-02 23:48 UTC
Labels: wontfix
