### ISSUE TITLE
Error: Cannot get file data without valid offset. FMV Error

### ISSUE THREAD

**Issue by FaithOriginalisme** [TexTools/FFXIV_TexTools_UI#139] opened 2022-01-22 01:46 UTC
2 Error Messages, wanted to pass them on

System.Exception: Encountered an error while updating body textures.

Error: Cannot get file data without valid offset.
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateBodyTextures>d__111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateSkin>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<AddModelToView>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

AAAAAND Here's the second one
 
======================================================
System.Exception: Encountered an error while updating body textures.

Error: Cannot get file data without valid offset.
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateBodyTextures>d__111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateSkin>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<AddModelToView>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FFXIV_TexTools.App.Main()
======================================================
Yes   No   
---------------------------

**Comment by KoraLyn** [comment] 2022-02-07 23:55
Could you give some steps to reproduce this error?

**Comment by ktrichel** [comment] 2022-06-14 11:03
[Report 2.txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/8899129/Report.2.txt)
[Report 3.txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/8899130/Report.3.txt)
[Report 1.txt](https://github.com/TexTools/FFXIV_TexTools_UI/files/8899131/Report.1.txt)

Hi, since I noticed this is seemingly an unsolved issue, I'm just commenting to add on that I am also receiving said errors (or at least similar) and it outputs to 3 seperate reports (see attached files). For me at least it only seems to occur with specific mods when attempting to move to FMV. I first noticed it after finding that certain models were missing in game, but when I checked the models they showed just fine which was when I pressed the add to FMV button and experienced the crash. I would like to provide whatever I can as I'd like to not keep this model disabled forever. :)

**Comment by Squall-Leonhart** [comment] 2022-12-13 22:59
If the items are missing in the FMV and in  game, you have an issue with mods, their installation or bad indexes, none of which are bugs in Textools.

Closing this because its out of date, and insufficient information was provided by the opener to investigate.

**Closed as not planned** 2022-12-13 22:59 UTC
