### ISSUE TITLE
Veena Face Textures arent listed in Modlist

### ISSUE THREAD

**Issue by Rias92** [TexTools/FFXIV_TexTools_UI#198] opened 2022-08-07 12:36 UTC
Im not able to export a TTMP that changes Veena Iris. Just the 4 Rava faces are exportable.

I originally wanted to create a TTMP that gives Veena makeup and Iris but it wasnt possible to export it. Face 0001(2,3,4) is viable face 0101(2,3,4) isnt

**Comment by Squall-Leonhart** [comment] 2022-08-25 06:28
duplicate of #134

**Closed as not planned** 2022-12-13 23:13 UTC
