### ISSUE TITLE
Cache ReBuild Error

### ISSUE THREAD

**Issue by haochidehuahua** [TexTools/FFXIV_TexTools_UI#79] opened 2021-08-11 14:57 UTC
An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

Non-negative number required.
Parameter name: count.

**Comment by horselwz** [comment] 2021-08-11 16:05
I have the same problem

**Comment by DOICY** [comment] 2021-08-12 11:25
I got the same！

**Comment by guquan2332** [comment] 2021-08-12 15:12
I have the same problem，why

**Comment by RavenGuo** [comment] 2021-08-12 23:52
I have the same problem, maybe we need to waite for an update.

**Comment by Jet-cmd** [comment] 2021-08-13 05:40
me too

**Comment by Squall-Leonhart** [comment] 2021-08-13 07:06
Duplicate of #78 

Chinese service players can use this dev build to solve this 
https://cdn.discordapp.com/attachments/368482175051366410/874579721797644288/FFXIV_TexTools_v2.3.6.2_dev.zip

**Comment by Squall-Leonhart** [comment] 2021-08-13 13:49
anyone had any game crashes with mods imported with that dev build?

**Comment by darkness-night** [comment] 2021-08-13 15:03
> anyone had any game crashes with mods imported with that dev build?

When I use this version to import the MOD, my game cannot start or it crashes after entering the password.

**Comment by Squall-Leonhart** [comment] 2021-08-13 15:09
do you have verifiable clean index backups?
what kind of mods are they?
what are the sizes of the game data files?

**Comment by gousanriku** [comment] 2021-08-13 15:23
> anyone had any game crashes with mods imported with that dev build?

size limit reached for DAT: 040000 Name: c0101e9903_sho.mdl Path: chara/equipment/e9903/model/c0101e9903_sho.mdl Import Stage: Data Writing Error: Maximum data size limit reached for DAT: 040000 Name: c0101e9903_glv.mdl Path: chara/equipment/e9903/model/c0101e9903_glv.mdl Import Stage: Data Writing Error: Maximum data size limit reached for DAT: 040000 Name: c0101e9903_dwn.mdl Path: chara/equipment/e9903/model/c0101e9903_dwn.mdl Import Stage: Data Writing Error: Maximum data size limit reached for DAT: 040000 Name: v01_c0101e9903_dwn_b_m.tex Path: chara/equipment/e9903/texture/v01_c0101e9903_dwn_b_m.tex Import Stage: Data Writing Error: Maximum data size limit reached for DAT: 040000 Name: v01_c0101e9903_dwn_b_n.tex Path: chara/equipment/e9903/texture/v01_c0101e9903_dwn_b_n.tex Import Stage: Data Writing Error: Maximum data size limit reached for DAT: 040000 Name: mt_c0101e9903_dwn_b.mtrl Path: chara/equipment/e9903/material/v0001/mt_c0101e9903_dwn_b.mtrl Import Stage: Data Writing Error: Maxim

When I use this version to import the MOD,There is always an error message like this.

**Comment by Squall-Leonhart** [comment] 2021-08-13 15:32
how many 040000 dats do you have and what are their sizes.

**Comment by Squall-Leonhart** [comment] 2021-08-13 15:55
https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip


@gousanriku try this

**Comment by haochidehuahua** [comment] 2021-08-13 16:11
> https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip
> 
> try this

Thank you very much.Problem solved.

**Comment by Squall-Leonhart** [comment] 2021-08-13 16:13
> > https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip
> > try this
> 
> Thank you very much.Problem solved.

please be sure to back up your sqpack folders before importing any mods just in case something is not 100% correct yet in this one, and test importing something.

**Comment by horselwz** [comment] 2021-08-13 18:14
yes it's works
thanks



At 2021-08-14 00:12:07, "haochidehuahua" ***@***.***> wrote:

https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip

try this

Thank you very much.Problem solved.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by horselwz** [comment] 2021-08-13 18:14
yes it's works
thanks



At 2021-08-14 00:13:56, "Squall Leonhart" ***@***.***> wrote:

https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip
try this

Thank you very much.Problem solved.

please be sure to back up your sqpack folders before importing any mods just in case something is not 100% correct yet in this one, and test importing something.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Squall-Leonhart** [comment] 2021-08-14 07:15
Thank you for the feedback, I apologize for the first test  build causing some issues.

For those of you who continue to have problems, you will need to obtain clean indexes and a copy of the 040000.win32.dat5 from a friend who keeps up to date clean backups, or fresh install the game.

If any of you have copy of the previous patches ffxivgame.ver file, you can delete the broken dat and force the launcher to redownload the 5.5 update, but i can only base this on the international launcher's behavior.

**Comment by guquan2332** [comment] 2021-08-14 14:42
> [Https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip](https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip)
> 
> @gousanriku尝尝这个

hank you very much. My problem has been solved.

**Comment by guquan2332** [comment] 2021-08-14 14:43
> [Https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip](https://cdn.discordapp.com/attachments/368482175051366410/875769419320688640/FFXIV_TexTools_v2.3.6.2_dev.zip)
> 
> @gousanriku尝尝这个

Thank you very much. My problem has been solved.

**Comment by KoraLyn** [comment] 2021-08-14 20:44
Should be resolved with the release of v2.3.6.2. Closing this issue, feel free to reopen if needed.

**Closed as completed by KoraLyn** 2021-08-14 20:44 UTC
