### ISSUE TITLE
Database Disk Image is malformed

### ISSUE THREAD

**Issue by WolfgerLynel** [TexTools/FFXIV_TexTools_UI#64] opened 2021-06-11 01:32 UTC
![unknown (1)](https://user-images.githubusercontent.com/85716728/121617549-d7081380-ca2a-11eb-9404-9ca1c96c3466.png)
![unknown](https://user-images.githubusercontent.com/85716728/121617552-d8394080-ca2a-11eb-8a68-932153ab427d.png)

This Error "Database Disk Image is Malformed" keeps popping up everytime i load up the tool. and somehow cuz of this error, i am unable to upload/import any other mod packs to have fun with. Why is this happening?

**Comment by WolfgerLynel** [comment] 2021-06-11 01:33
![unknown](https://user-images.githubusercontent.com/85716728/121617669-15053780-ca2b-11eb-91ab-75c522081a2b.png)

**Comment by KoraLyn** [comment] 2021-07-04 22:05
Seems like somehow your database file got corrupted. I'd recommend uninstalling and reinstalling TexTools to see if that fixes the database error.

**Comment by WolfgerLynel** [comment] 2021-07-04 22:22
I have tried that before, and the same error comes up. It wasn't fix until
I reinstall final fantasy 14 (which was a whole day hassle) but then after
a while it came up again. I refused to believe it's because I have the
files on an external hard drive cuz it never started doing this to me. It
started when I recently only NOW installed the companion app on my phone
and linked it to my account.

**Comment by KoraLyn** [comment] 2021-07-23 21:20
Installing an app on your phone and linking it to your account is completely unrelated to any of this. Your game being on an external drive could very well be the cause and I would generally not recommend doing it. It's possible the drive was disconnected  while TexTools was processing the dependency queue in the background corrupting the database in the process.

I'm closing this issue, these kinds of errors are easier dealt with by joining the Discord (https://discord.gg/ffxivtextools) and asking in the appropriate help channel.

**Closed as completed by KoraLyn** 2021-07-23 21:20 UTC
