### ISSUE TITLE
Graphical corruption in menu and list text

### ISSUE THREAD

**Issue by zorael** [TexTools/FFXIV_TexTools_UI#69] opened 2021-07-14 12:40 UTC
x86_64, Windows 10 is up to date as of 21-07-14. Nvidia 2070 Super running 471.11 (latest). Both the stable 2.3.5.10 and the current 2.3.6.0 beta tested.

When I mouseover entries in the menu and in the drop-down item lists, the text often disappears as the cursor leaves them. Rebooting does not solve it. See attached clip.

I haven't been playing for a while so I don't know when this started, sadly.

https://user-images.githubusercontent.com/1975169/125623276-828518af-8513-4640-b374-1df6552b69bd.mp4

**Comment by Squall-Leonhart** [comment] 2021-07-16 23:22
Can you try disabling MPO's using the Reg files attached to the following https://nvidia.custhelp.com/app/answers/detail/a_id/5157/


If it doesn't help, turn them back on,  a potential fix for this will be to  update the theme libraries for ControlzEX and MahApps

**Comment by zorael** [comment] 2021-07-18 21:41
I tried disabling them and rebooting, but the behaviour persists.

Curiously, if I log into a different recently-created user (in Windows) and start TexTools as them, everything behaves as it should. Not sure if that is of any relevance.

**Comment by Squall-Leonhart** [comment] 2021-07-19 01:52
Its very much of relevance, it means theres a user setting or loaded software connected to the issue.

**Comment by Squall-Leonhart** [comment] 2021-07-19 02:17
The issue is being caused by an outdated  Nahimic audio enhancements, bundled with things such as sonic studio 3 and Realtek HD Audio.

**Comment by Squall-Leonhart** [comment] 2021-07-19 02:46
https://github.com/fork-dev/TrackerWin/issues/1232

**Comment by KoraLyn** [comment] 2021-07-23 21:26
As mentioned this seems to be related to some kind of interference by Nahimic software in WPF. 

Closing this issue since this won't be fixed by us.

**Closed as completed by KoraLyn** 2021-07-23 21:26 UTC
