### ISSUE TITLE
"Apply Deformation Shapes" ignored in FMV.

### ISSUE THREAD

**Issue by Katsuki22** [TexTools/FFXIV_TexTools_UI#75] opened 2021-08-02 19:51 UTC
Hi. I have a little problem when applying deformation shapes to a model, the changes are totally ignored when opening the model in the FMV.
I don't know what to do to fix the problem. Does anyone know how to do this, please?
This question has already been asked but no answer was given.
Thank you for your answers.

**Comment by Nekkowe** [comment] 2021-11-08 00:18
I can confirm this, it's happening to me too. It also affects the model export, which is a problem.

Left: no shapes applied, Right, shapes applied:
![image](https://user-images.githubusercontent.com/28980049/140667557-41526301-6f30-4829-b7b1-c31a0912d48b.png)

Exported model missing the deformations, note the eyebrows:
![image](https://user-images.githubusercontent.com/28980049/140667578-64ee0a17-e74c-478d-9c2e-b326ade39f28.png)

**Comment by Nekkowe** [comment] 2021-11-08 00:39
My mistake, turns out the exported FBX file *does* contain the deformation shapes.

If anyone else runs into this issue: in Blender, the deformation shapes are stored as Shape Keys, so you just drag the relevant sliders to 1.0:
![image](https://user-images.githubusercontent.com/28980049/140668349-68f73f62-4a2d-44ef-88ec-f60059cdfc23.png)

That said, the issue with the FMV preview persists

**Comment by Lunaretic** [comment] 2024-06-20 06:15
Closing this issue as a will-not-fix since there is no intention at this time to enable shapes for the FMV itself, and the FMV export already includes the shape morphs.

**Closed as not planned by Lunaretic** 2024-06-20 06:15 UTC
